services:
  backend:
    image: python:3.10 
    container_name: backend
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./Backend:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn fast_api:app --host 0.0.0.0 --port 8000 --reload"


  frontend:
    image: node:18
    container_name: frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./Frontend:/app
    command: bash -c "npm install && npm run dev"
    # depends_on:
    #   - backend
